org: sholguinc
app: aws-node-http-project
service: aws-node-http-project
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
#  stage: dev
#  profile: some-profile
#  region: us-east-1
  timeout: 30
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    httpPort: ${env:SERVERLESS_OFFLINE_PORT, 3000}

functions:
  api:
    handler: dist/main.handler
    events:
      - httpApi: '*'
